services:
  - type: worker
    runtime: docker
    name: gustmarket-scraper-worker-queue
    region: ohio
    env: python
    dockerCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: gustmarket-scraper-worker-redis
          type: redis
          property: connectionString
  - type: worker
    runtime: docker
    name: gustmarket-scraper-worker-beat
    region: ohio
    env: python
    dockerCommand: "celery --app tasks beat --loglevel info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: gustmarket-scraper-worker-redis
          type: redis
          property: connectionString
  - type: web
    name: gustmarket-scraper-worker-app
    region: ohio
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: gustmarket-scraper-worker-redis
          type: redis
          property: connectionString
  - type: web
    name: gustmarket-scraper-worker-flower
    region: ohio
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery flower --app tasks --loglevel info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: gustmarket-scraper-worker-redis
          property: connectionString
  - type: redis
    name: gustmarket-scraper-worker-redis
    region: ohio
    plan: starter # we choose a plan with persistence to ensure tasks are not lost upon restart
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections
