
color_list = [
    'red', 'rouge',
    'orange', 'orange',
    'yellow', 'jaune',
    'green', 'vert',
    'blue', 'bleu',
    'purple', 'violet',
    'pink', 'rose',
    'brown', 'marron',
    'gray', 'gris',
    'black', 'noir',
    'white', 'blanc',
    'cyan', 'cyan',
    'magenta', 'magenta',
    'turquoise', 'turquoise',
    'lime', 'citron vert',
    'indigo', 'indigo',
    'gold', 'or',
    'silver', 'argent',
    'bronze', 'bronze',
    'teal', 'sarcelle',
    'lavender', 'lavande',
    'maroon', 'bordeaux',
    'navy', 'marine',
    'olive', 'olive',
    'coral', 'corail',
    'peach', 'pêche',
    'periwinkle', 'bleuet',
    'mint', 'dark grey',
    'grey',
    'dark gray',
    'gray',
    'menthe', 'vanille',
    'aqua',
    'onyxmint',
    'mint/onyx',
    'mint / onyx',
    'onyxflame',
    'onyx/flame',
    'onyx / flame',
    'abyssflame',
    'abyss/flame'
    'abyss / flame',
    'onyx'
    # Add more color strings as needed
]
